### ISSUE TITLE
[BUG] yarn preview failing

### ISSUE THREAD

**Issue by stuartwk** [dev-protocol/clubs-core#144]
### Description

ui-preview/astro.config.mjs is trying to load config from src/astro.config.mjs, which does not exist.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aggre** [comment]
I found a problem that it breaks an Astro project (like clubsx) if it calls any Astro plugin internally to export Astro config presets. So I removed the presets from clubs-core.

For the reason, we need to define an Astro config statically for ui-preview.
